
REG_ACC   = 'ACC'
REG_BAK   = 'BAK'
REG_NIL   = 'NIL'
REG_LEFT  = 'LEFT'
REG_RIGHT = 'RIGHT'
REG_UP    = 'UP'
REG_DOWN  = 'DOWN'
REG_ANY   = 'ANY'
REG_LAST  = 'LAST'

REGISTERS_SET = [
    REG_ACC, REG_BAK, REG_NIL, REG_LEFT, REG_RIGHT, REG_UP, REG_DOWN,
    REG_ANY, REG_LAST
]

INSTR_NOP = 'NOP'
INSTR_MOV = 'MOV'
INSTR_SWP = 'SWP'
INSTR_SAV = 'SAV'
INSTR_ADD = 'ADD'
INSTR_SUB = 'SUB'
INSTR_NEG = 'NEG'
INSTR_JMP = 'JMP'
INSTR_JEZ = 'JEZ'
INSTR_JNZ = 'JNZ'
INSTR_JGZ = 'JGZ'
INSTR_JLZ = 'JLZ'
INSTR_JRO = 'JRO'
INSTR_HALT = 'HALT'
INSTR_LABEL = 'LABEL'

INSTRUCTIONS_SET = [
    INSTR_NOP, INSTR_MOV, INSTR_SWP, INSTR_SAV, INSTR_ADD, INSTR_SUB, INSTR_NEG,
    INSTR_JMP, INSTR_JEZ, INSTR_JNZ, INSTR_JGZ, INSTR_JLZ, INSTR_JRO,
    INSTR_HALT, INSTR_LABEL
]

TYPE_LABEL = 'LABEL'

SRC_TYPE_NONE  = 0
SRC_TYPE_REG   = 1
SRC_TYPE_INT   = 2
SRC_TYPE_LABEL = 3
SRC_TYPE_ERR   = 4


# int const
NODE_MAX_INSTR = 15
INT_MAX =  999
INT_MIN = -999

WIDTH  = 4
HEIGHT = 3


# directions, positions
NODE_MAP = [
    0, 1, 2, 3,
    4, 5, 6, 7,
    8, 9, 10, 11
]



PORT_REGISTERS = [
    REG_LEFT, REG_RIGHT, REG_UP, REG_DOWN, REG_ANY, REG_LAST
]

PORT_LEFT  = 'LEFT'
PORT_RIGHT = 'RIGHT'
PORT_UP    = 'UP'
PORT_DOWN  = 'DOWN'

PORTS_LIST = [
    PORT_LEFT, PORT_RIGHT, PORT_UP, PORT_DOWN
]


# states
NODE_STATE_IDLE  = 'IDLE'
NODE_STATE_RUN   = 'RUN'
NODE_STATE_READ  = 'READ'
NODE_STATE_WRITE = 'WRTE'

NODE_STATES = [NODE_STATE_IDLE, NODE_STATE_RUN, NODE_STATE_READ, NODE_STATE_WRITE]